[2025-06-13T03:10:35.111+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-13T03:10:35.131+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: payparser_pipeline_dag.process_new_images manual__2025-06-13T03:10:33.372592+00:00 [queued]>
[2025-06-13T03:10:35.141+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: payparser_pipeline_dag.process_new_images manual__2025-06-13T03:10:33.372592+00:00 [queued]>
[2025-06-13T03:10:35.142+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-06-13T03:10:35.157+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): process_new_images> on 2025-06-13 03:10:33.372592+00:00
[2025-06-13T03:10:35.163+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=203) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-13T03:10:35.166+0000] {standard_task_runner.py:72} INFO - Started process 204 to run task
[2025-06-13T03:10:35.167+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'payparser_pipeline_dag', 'process_new_images', 'manual__2025-06-13T03:10:33.372592+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/payparser_dag.py', '--cfg-path', '/tmp/tmpd1450sv8']
[2025-06-13T03:10:35.170+0000] {standard_task_runner.py:105} INFO - Job 69: Subtask process_new_images
[2025-06-13T03:10:35.223+0000] {task_command.py:467} INFO - Running <TaskInstance: payparser_pipeline_dag.process_new_images manual__2025-06-13T03:10:33.372592+00:00 [running]> on host 9b9192f456bf
[2025-06-13T03:10:35.305+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='zain' AIRFLOW_CTX_DAG_ID='payparser_pipeline_dag' AIRFLOW_CTX_TASK_ID='process_new_images' AIRFLOW_CTX_EXECUTION_DATE='2025-06-13T03:10:33.372592+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-13T03:10:33.372592+00:00'
[2025-06-13T03:10:35.306+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-06-13T03:10:35.328+0000] {logging_mixin.py:190} INFO - ⏳ Processing image: /opt/***/shared/downloads/WhatsApp Image 2025-06-12 at 00.30.14_a8346959.jpg
[2025-06-13T03:10:36.495+0000] {logging_mixin.py:190} INFO - Database error: unable to open database file
[2025-06-13T03:10:36.496+0000] {logging_mixin.py:190} INFO - ❌ Error processing WhatsApp Image 2025-06-12 at 00.30.14_a8346959.jpg: cannot access local variable 'conn' where it is not associated with a value
[2025-06-13T03:10:36.497+0000] {logging_mixin.py:190} INFO - ⏳ Processing image: /opt/***/shared/downloads/WhatsApp Image 2025-06-12 at 23.10.05_0c4f87f3.jpg
[2025-06-13T03:10:37.658+0000] {logging_mixin.py:190} INFO - Database error: unable to open database file
[2025-06-13T03:10:37.658+0000] {logging_mixin.py:190} INFO - ❌ Error processing WhatsApp Image 2025-06-12 at 23.10.05_0c4f87f3.jpg: cannot access local variable 'conn' where it is not associated with a value
[2025-06-13T03:10:37.658+0000] {logging_mixin.py:190} INFO - ⏳ Processing image: /opt/***/shared/downloads/WhatsApp Image 2025-06-13 at 01.34.27_5af07ffa.jpg
[2025-06-13T03:10:39.161+0000] {logging_mixin.py:190} INFO - Database error: unable to open database file
[2025-06-13T03:10:39.162+0000] {logging_mixin.py:190} INFO - ❌ Error processing WhatsApp Image 2025-06-13 at 01.34.27_5af07ffa.jpg: cannot access local variable 'conn' where it is not associated with a value
[2025-06-13T03:10:39.165+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-06-13T03:10:39.175+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-06-13T03:10:39.175+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=payparser_pipeline_dag, task_id=process_new_images, run_id=manual__2025-06-13T03:10:33.372592+00:00, execution_date=20250613T031033, start_date=20250613T031035, end_date=20250613T031039
[2025-06-13T03:10:39.234+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-06-13T03:10:39.249+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-13T03:10:39.252+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
