[2025-06-13T03:52:09.926+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-13T03:52:09.947+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: payparser_pipeline_dag.cash_processing_task scheduled__2025-06-13T03:50:00+00:00 [queued]>
[2025-06-13T03:52:09.956+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: payparser_pipeline_dag.cash_processing_task scheduled__2025-06-13T03:50:00+00:00 [queued]>
[2025-06-13T03:52:09.956+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-06-13T03:52:09.973+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): cash_processing_task> on 2025-06-13 03:50:00+00:00
[2025-06-13T03:52:09.979+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=163) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-13T03:52:09.981+0000] {standard_task_runner.py:72} INFO - Started process 166 to run task
[2025-06-13T03:52:09.981+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'payparser_pipeline_dag', 'cash_processing_task', 'scheduled__2025-06-13T03:50:00+00:00', '--job-id', '149', '--raw', '--subdir', 'DAGS_FOLDER/payparser_dag.py', '--cfg-path', '/tmp/tmplq8ms6i4']
[2025-06-13T03:52:09.984+0000] {standard_task_runner.py:105} INFO - Job 149: Subtask cash_processing_task
[2025-06-13T03:52:10.046+0000] {task_command.py:467} INFO - Running <TaskInstance: payparser_pipeline_dag.cash_processing_task scheduled__2025-06-13T03:50:00+00:00 [running]> on host 99fad00d6fef
[2025-06-13T03:52:10.137+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='zain' AIRFLOW_CTX_DAG_ID='payparser_pipeline_dag' AIRFLOW_CTX_TASK_ID='cash_processing_task' AIRFLOW_CTX_EXECUTION_DATE='2025-06-13T03:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-13T03:50:00+00:00'
[2025-06-13T03:52:10.139+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-06-13T03:52:10.168+0000] {logging_mixin.py:190} INFO - Database error: UNIQUE constraint failed: transactions.transaction_id
[2025-06-13T03:52:10.170+0000] {logging_mixin.py:190} INFO - ✅ Cash transaction inserted: {'amount': '9880', 'sender': 'Test', 'receiver_name': 'Unknown', 'phone_number': '01007041192', 'date': '2025-06-12 12:30', 'transaction_id': '012233325194', 'status': 'completed'}
[2025-06-13T03:52:10.175+0000] {logging_mixin.py:190} INFO - Database error: UNIQUE constraint failed: transactions.transaction_id
[2025-06-13T03:52:10.177+0000] {logging_mixin.py:190} INFO - ✅ Cash transaction inserted: {'amount': '9880', 'sender': 'Test', 'receiver_name': 'Unknown', 'phone_number': '01033962186', 'date': '2025-06-12 11:09', 'transaction_id': '012246503080', 'status': 'completed'}
[2025-06-13T03:52:10.182+0000] {logging_mixin.py:190} INFO - Database error: UNIQUE constraint failed: transactions.transaction_id
[2025-06-13T03:52:10.183+0000] {logging_mixin.py:190} INFO - ✅ Cash transaction inserted: {'amount': '1900', 'sender': 'Test', 'receiver_name': 'Unknown', 'phone_number': '01096753345', 'date': '2025-06-13 01:34', 'transaction_id': '012248429672', 'status': 'completed'}
[2025-06-13T03:52:10.184+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-06-13T03:52:10.195+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-06-13T03:52:10.195+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=payparser_pipeline_dag, task_id=cash_processing_task, run_id=scheduled__2025-06-13T03:50:00+00:00, execution_date=20250613T035000, start_date=20250613T035209, end_date=20250613T035210
[2025-06-13T03:52:10.236+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-06-13T03:52:10.244+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
